### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by RavenousMonkeey** [Alexyoe/Reddit-on-Google-Search#1]
The reddit button doesn't show up anymore. Can you please update the script? Thank you!

**Comment by Alexyoe** [comment]
Is the button not showing up at all? or is it hidden behind the the right chevron?

**Comment by nekato** [comment]
Doesn't show up at all.

**Comment by Alexyoe** [comment]
Strange, it still seems to be working on my end. What browser are you using the script on?

**Comment by nekato** [comment]
Latest chrome.

**Comment by Alexyoe** [comment]
I just published a new version. It should be updated on greasy monkey any time now. Let me know if that fixes anything for you.

**Comment by nekato** [comment]
Updated it, but it still doesn't work, even with all other extensions disabled. But thank you for trying. Appreciate it.

**Comment by Alexyoe** [comment]
Just released another new version as Google updated search again. Hopefully this fixes it for you.

**Comment by nekato** [comment]
It works! Great job.

**Comment by Alexyoe** [comment]
Awesome, glad it is working again! If you run into any issues please let me know!
